import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../data/models/item_model.dart';
import '../../logic/inventory_provider.dart';

class AddEditItemDialog extends StatefulWidget{final ItemModel? item;const AddEditItemDialog({super.key,this.item});@override State<AddEditItemDialog> createState()=>_State();}
class _State extends State<AddEditItemDialog>{
 final key=GlobalKey<FormState>();late TextEditingController name,barcode,sell,cost,qty,expiry,notes;String category='تلفونات';bool saving=false;static const cats=['تلفونات','إكسسوارات','قطع غيار','عام'];
 @override void initState(){super.initState();final x=widget.item;name=TextEditingController(text:x?.name??'');barcode=TextEditingController(text:x?.barcode??'');sell=TextEditingController(text:x==null?'':x.sellPrice.toString());cost=TextEditingController(text:x==null?'':x.costPrice.toString());qty=TextEditingController(text:x==null?'0':x.quantity.toString());expiry=TextEditingController(text:x?.expiryDate??'');notes=TextEditingController(text:x?.notes??'');if(x!=null&&cats.contains(x.category))category=x.category;}
 @override void dispose(){for(final c in[name,barcode,sell,cost,qty,expiry,notes])c.dispose();super.dispose();}
 Future<void> date()async{final p=await showDatePicker(context:context,initialDate:DateTime.tryParse(expiry.text)??DateTime.now(),firstDate:DateTime.now(),lastDate:DateTime(2100),locale:const Locale('ar','SA'));if(p!=null){expiry.text=p.year.toString().padLeft(4,'0')+'-'+p.month.toString().padLeft(2,'0')+'-'+p.day.toString().padLeft(2,'0');setState((){});}}
 Future<void> save()async{if(!key.currentState!.validate())return;final sp=double.tryParse(sell.text),cp=double.tryParse(cost.text)??0,q=int.tryParse(qty.text);if(sp==null||sp<0||cp<0||q==null||q<0)return;setState(()=>saving=true);final ok=await context.read<InventoryProvider>().saveItem(ItemModel(id:widget.item?.id,name:name.text.trim(),category:category,barcode:barcode.text.trim().isEmpty?null:barcode.text.trim(),sellPrice:sp,costPrice:cp,quantity:q,expiryDate:expiry.text.trim().isEmpty?null:expiry.text.trim(),notes:notes.text.trim().isEmpty?null:notes.text.trim()));if(!mounted)return;if(ok)Navigator.pop(context);else setState(()=>saving=false);}
 InputDecoration d(String s,IconData i)=>InputDecoration(labelText:s,prefixIcon:Icon(i),border:const OutlineInputBorder());
 @override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:AlertDialog(title:Text(widget.item==null?'إضافة صنف جديد':'تعديل بيانات الصنف',style:const TextStyle(fontWeight:FontWeight.bold)),content:SizedBox(width:MediaQuery.sizeOf(c).width*.9,child:SingleChildScrollView(child:Form(key:key,child:Column(mainAxisSize:MainAxisSize.min,children:[
 TextFormField(controller:name,decoration:d('اسم الصنف *',Icons.shopping_bag_outlined),validator:(v)=>v==null||v.trim().isEmpty?'مطلوب':null),const SizedBox(height:12),
 DropdownButtonFormField<String>(value:category,decoration:d('مجموعة الصنف',Icons.category_outlined),items:cats.map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:saving?null:(x)=>setState(()=>category=x!)),const SizedBox(height:12),
 TextFormField(controller:barcode,textDirection:TextDirection.ltr,decoration:d('رمز الصنف / الباركود',Icons.qr_code_scanner)),const SizedBox(height:12),
 Row(children:[Expanded(child:TextFormField(controller:sell,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:d('سعر البيع *',Icons.payments_outlined),validator:(v)=>double.tryParse(v??'')==null?'غير صحيح':null)),const SizedBox(width:8),Expanded(child:TextFormField(controller:cost,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:d('سعر التكلفة',Icons.money_off_outlined)))]),const SizedBox(height:12),
 Row(children:[Expanded(child:TextFormField(controller:qty,keyboardType:TextInputType.number,decoration:d('الكمية الحالية',Icons.inventory_2_outlined),validator:(v)=>int.tryParse(v??'')==null?'غير صحيحة':null)),const SizedBox(width:8),Expanded(child:TextFormField(controller:expiry,readOnly:true,onTap:saving?null:date,decoration:d('تاريخ الانتهاء',Icons.calendar_today_outlined)))]),const SizedBox(height:12),
 TextFormField(controller:notes,maxLines:3,decoration:d('الملاحظات / المواصفات',Icons.notes))])))),actions:[TextButton(onPressed:saving?null:()=>Navigator.pop(c),child:const Text('إلغاء')),FilledButton(onPressed:saving?null:save,child:saving?const SizedBox(width:20,height:20,child:CircularProgressIndicator(strokeWidth:2)):const Text('موافق / حفظ'))]));
}